const mongoose = require("mongoose");

const releaseEntrySchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ["add", "fix", "update"],
      default: "update",
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
      trim: true,
    },
    tags: {
      type: [String],
      default: [],
    },
    imageUrl: {
      type: String,
      default: "",
      trim: true,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    groupDate: {
      type: String,
      default: "",
      trim: true,
    },
    previewItems: {
      type: [
        new mongoose.Schema(
          {
            label: {
              type: String,
              required: true,
              trim: true,
            },
            imageUrl: {
              type: String,
              default: "",
              trim: true,
            },
          },
          { _id: false }
        ),
      ],
      default: [],
    },
  },
  { _id: false }
);

const releaseSchema = new mongoose.Schema(
  {
    version: {
      type: String,
      required: true,
      trim: true,
    },
    monthLabel: {
      type: String,
      required: true,
      trim: true,
    },
    entries: {
      type: [releaseEntrySchema],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.models.Release || mongoose.model("Release", releaseSchema);
